# Generated by Django 6.0 on 2025-12-25 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_doctor_license_image_doctor_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="license_image",
            field=models.ImageField(blank=True, null=True, upload_to="licenses/"),
        ),
        migrations.AddField(
            model_name="doctorverification",
            name="license_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="licenses/verifications/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="license_image",
            field=models.ImageField(blank=True, null=True, upload_to="licenses/users/"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
