# Generated by Django 6.0 on 2025-12-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_doctor_license_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="license_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctorverification",
            name="license_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="license_image",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
