# Generated by Django 6.0 on 2025-12-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_doctor_license_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="license_image_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorverification",
            name="license_image_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
