# Generated by Django 6.0 on 2025-12-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_doctor_license_image_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="license_image_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="license_image_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="doctorverification",
            name="license_image_size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
