# Generated by Django 6.0 on 2025-12-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_license_image_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="license_image_size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
