# Generated by Django 6.0 on 2025-12-25 18:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_created_at_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetinalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_by_type",
                    models.CharField(
                        choices=[("patient", "Patient"), ("doctor", "Doctor")],
                        max_length=10,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("retinal_image", models.BinaryField(blank=True, null=True)),
                ("retinal_image_size", models.IntegerField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retinal_images",
                        to="accounts.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retinal_images",
                        to="accounts.patient",
                    ),
                ),
            ],
        ),
    ]
