# Generated by Django 6.0.2 on 2026-02-06 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_retinalimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="retinalimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
