# Generated by Django 4.2 on 2026-02-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_profile_image_user_profile_image_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="retinalimage",
            name="selected_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_retinal_images",
                to="accounts.doctor",
            ),
        ),
    ]
